### ISSUE TITLE
Possibility to decide switch or leak sensor

### ISSUE THREAD

**Issue by Lling** [chefhl/homebridge-plugin-netatmo-rain-sensor#1]
**Is your feature request related to a problem? Please describe:**
At the beginning, the plugin created a leak sensor. With the V2 this was changed to a switch.
Would it be possible to have a option how the plugin should display the sensor?

**Describe the solution you'd like:**
Option 1: Leak Sensor
Option 2: Switch

**Comment by chefhl** [comment]
First of all thanks @Lling for the feedback - I think it's a great idea!
I have not made the decision to switch to a "Switch" lightly. In the end I just thought it is too annoying to get the iOS internal "Leak" notification every time rain was detected.
Nevertheless I will definitely try to make the device type configurable as proposed - in fact I have been thinking in the same direction. So thanks again for the feedback which is always welcome.

**Comment by chefhl** [comment]
Just published version 2.1.0 of the plugin that allows the device type selection.
